#.travis.yml

language: node_js

node_js:
  - "node"

addons:
  chrome: stable

before_script:
  - set -e
  - npm install -g @angular/cli
  - npm install -g codeclimate-test-reporter
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - ng build --prod

after_script:
  - ng test --watch=false --code-coverage
  - codeclimate-test-reporter < coverage/lcov.info
  - npm install -g --silent firebase-tools

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token $FIREBASE_DEPLOY --non-interactive


notifications:
  email:
    on_failure: change
    on_success: change
webhooks: https://fathomless-fjord-24024.herokuapp.com/notify