#.travis.yml

language: node_js

node_js:
  - "8.2.1"

branches:
  only:
  - gh-pages
  - /.*/

env:
  global:
    - CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage
    - CODECLIMATE_REPO_TOKEN=4368e3d4-20fc-4d27-ae50-fe3492ca6200

before_script:
  - set -e
  - npm install -g @angular/cli
  - npm install -g codeclimate-test-reporter
  - npm install

script:
  - ng build --prod

after_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ng test --watch=false --code-coverage
  - codeclimate-test-reporter < coverage/lcov.info

notifications:
  email:
    on_failure: change
    on_success: change
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
